### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by officeabg** [StorytellerCZ/Socialize-starter#1]
Hi Jan!
This is awesome!!! I was looking in @copleykj 's repo to find this! I even emailed to ask if he has an agregator project  of his goodies like this one on!
Please tell me if you are looking to develop this further as it is very very cool what you did this far.

Thanks!

**Comment by StorytellerCZ** [comment]
Hi @officeabg,

Yes, I'm looking to develop this further pending time constraints (since I started in the workforce). Right now I'm waiting for the next Meteor 1.4 beta to fix an outstanding issue.

**Comment by officeabg** [comment]
Hi! I joined the socialize slack chanel and I saw you there! If you have some updates please share there :)

**Comment by StorytellerCZ** [comment]
Created a channel in the Slack called `socialize-starter` if you have any specific question related to this project.
