### ISSUE TITLE
error when running the project

### ISSUE THREAD

**Issue by matwii** [StorytellerCZ/Socialize-starter#4]
when I have cloned the project and typed meteor I am getting this error:
`/home/matz/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:165
      throw error;
      ^

Error: ENOENT: no such file or directory, open '/tmp/mt-kx0r3i/os.json'
    at Error (native)
`

**Comment by StorytellerCZ** [comment]
Hi, thanks for the notice, I have a couple of updates coming up, I will release a new beta soon.

**Comment by StorytellerCZ** [comment]
I'm releasing a new beta with some updates right now. Also make sure that you have installed npm packages via: `meteor npm install`.
